- name: check if cargo is installed
  shell: command -v cargo
  register: cargo_exists
  ignore_errors: yes



- name: Download rustup installer
  when: cargo_exists is failed
  get_url:
    url: https://sh.rustup.rs
    dest: /tmp/rustup.sh.rs
    mode: '0755'
    force: 'yes'


- name: Install Rust and Cargo
  when: cargo_exists is failed
  shell: |
    /tmp/rustup.sh.rs -y


- name: Add Cargo bin to PATH in .bashrc
  lineinfile:
    path: /root/.bashrc
    line: 'export PATH="$HOME/.cargo/bin:$PATH"'
    create: yes
  become: yes
  become_user: root

