# -*- mode: ruby -*-
# vi: set ft=ruby :


Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu2204"
  config.vm.box_version = "4.3.12"
  config.ssh.forward_agent = true
  
  config.vm.provision "file", source: "ssh/root_key.pub", destination: "/home/vagrant/auth"
  config.vm.provision "shell", inline: <<-SHELL
    mkdir -p /root/.ssh
    chmod 700 /root/.ssh

    cat /home/vagrant/auth >> /root/.ssh/authorized_keys
    chmod 600 /root/.ssh/authorized_keys
  SHELL

  # 8G 4c
  config.vm.provider "libvirt" do |vb|
    vb.memory = "16384"
    vb.cpus = 8
  end

end
